title: Christopher Kittel
description: Open Data Science
author: Christopher Kittel
github: https://github.com/chreman
about: I push buttons on the internet.
#disqus_shortname:
#google_analytics:

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /projects/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/chris_kittel"
    # - icon: fa-linkedin
    #   link: "#"
    # - icon: fa-stack-exchange
    #   link: "#"
academic:
    - icon: ai-orcid
      link: "http://orcid.org/0000-0002-1894-5040"

share:
  twitter_username: chris_kittel

urls:
    - text: About Me
      url: /about/
    - text: Blog
      url: /
    - text: Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://chreman.github.io"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
